--- 
-   name: Environment for server
    hosts: server
    become: yes
    remote_user: entrant
    
    tasks:
        -   name: Install aptitude using apt
            apt: 
                name: aptitude
                state: latest
                update_cache: yes
                force_apt_get: yes

        -   name: Install required system packages
            apt: 
                name: 
                    - apt-transport-https
                    - ca-certificates
                    - curl
                    - software-properties-common
                    - python3-pip
                    - virtualenv
                    - python3-setuptools
                state: latest 
                update_cache: yes

        -   name: Add Docker GPG apt Key
            apt_key:
                url: https://download.docker.com/linux/ubuntu/gpg
                state: present

        -   name: Add Docker Repository
            apt_repository:
                repo: deb https://download.docker.com/linux/ubuntu bionic stable
                state: present

        -   name: Update apt packages
            apt:
                update_cache: yes

        -   name: Install docker-ce
            apt: 
                name: docker-ce
                state: latest
            notify: Start docker on boot
            
            
        -   name: Install Docker Compose
            get_url:
                url: https://github.com/docker/compose/releases/download/1.28.6/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
                dest: /usr/local/bin/docker-compose
                mode: '+x'

        -   name: Install Docker Module for Python
            pip:
                name: docker
            
                  
    handlers:
        -   name: Start docker on boot
            systemd:
                name: docker
                state: started
                enabled: yes