all:
  hosts:
    server:
      ansible_connection: ssh
      ansible_user: entrant
      ansible_ssh_pass: D&U5tvi68cwMySqkMLC2s=&a
      sudo: yes
      ansible_host: 178.154.204.29
      ansible_port: 22
      