# Generated by Django 3.1.7 on 2021-03-26 13:27

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.PositiveIntegerField(default=0, unique=True)),
                ('courier_type', models.CharField(blank=True, choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=4)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=0), blank=True, default=list, size=None)),
                ('working_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11, null=True), blank=True, default=list, size=None)),
                ('rating', models.FloatField(default=0, null=True)),
                ('earnings', models.PositiveIntegerField(default=0, null=True)),
                ('have_weight', models.FloatField(default=0)),
                ('last_order_time', models.CharField(default='', max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(default=0, unique=True)),
                ('weight', models.FloatField(default=0)),
                ('region', models.PositiveIntegerField(default=0)),
                ('complete_time', models.CharField(default='', max_length=28)),
                ('assign_time', models.CharField(default='', max_length=28)),
                ('delivery_time', models.PositiveIntegerField(default=0)),
                ('courier', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.courier')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(default=0, unique=True)),
                ('weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(50.0)])),
                ('region', models.PositiveIntegerField(default=0)),
                ('delivery_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), size=None)),
                ('assign_time', models.CharField(default='', max_length=28)),
                ('courier_coefficient', models.PositiveIntegerField(default=0)),
                ('courier', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.courier')),
            ],
        ),
    ]
